### PR TITLE
fixed camera bug

### LINKED ISSUE #20: Mock camera producer performance
The mock camera producer does not produce images at the requested rate.

### PR DESCRIPTION
**Pull request by PraneethSomisetty1**
- bug found: manager was polling at 33ms, and mock camera was throttling at 33.333ms so every other frame was being skipped.
- floored throttling time, and added tolerance at check for emitting record

Resolves #20

### CODE REVIEW

**Comment by PraneethSomisetty1** [comment]
* **#41** <a href="https://app.graphite.com/github/pr/TrossenRobotics/trossen_sdk/41?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#40** <a href="https://app.graphite.com/github/pr/TrossenRobotics/trossen_sdk/40?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#39** <a href="https://app.graphite.com/github/pr/TrossenRobotics/trossen_sdk/39?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/TrossenRobotics/trossen_sdk/39?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

File: src/hw/camera/mock_producer.cpp [hunk 1]
```diff
@@ -39,33 +43,44 @@ MockCameraProducer::MockCameraProducer(Config cfg) : cfg_(std::move(cfg)) {
...
   uint64_t now_mono = data::now_mono().to_ns();
-  if (last_emit_mono_ != 0) {
-    uint64_t dt = now_mono - last_emit_mono_;
-    if (intervals_ns_.size() < kMaxIntervals) intervals_ns_.push_back(dt);
-  }
+  
+  // Check if enough time has passed since last emit
+  // Use a small tolerance (1ms = 1,000,000ns) to account for scheduler timing jitter
+  // This prevents missing frames when polling period closely matches frame period
+  // not sure if this is the best practice but i get 148 frames out of 150 for 5 seconds at 30 fps
```
Comment (lukeschmitt-tr) [inline src/hw/camera/mock_producer.cpp]: Make this comment read more formally and readdress once you have more context

File: src/hw/camera/mock_producer.cpp [hunk 2]
```diff
@@ -39,33 +43,44 @@ MockCameraProducer::MockCameraProducer(Config cfg) : cfg_(std::move(cfg)) {
...
   }
 
+  if (warmup_remaining_ > 0) {
+    cv::Mat frame(cfg_.height, cfg_.width, CV_8UC3);
+    generate_frame(frame);
+    --warmup_remaining_;
+    ++stats_.warmup_discarded;
+    last_emit_mono_ = now_mono;
+    return;
+  }
```
[the remark this answers is not in the document]
Comment (lukeschmitt-tr) [reply src/hw/camera/mock_producer.cpp:66]: I would echo this comment. Why has this been moved up here? Why has `generate_frame` been added to this block?

**Review by lukeschmitt-tr — CHANGES_REQUESTED** [review]

File: src/hw/camera/mock_producer.cpp (hunk 1 above)
Comment (PraneethSomisetty1) [reply src/hw/camera/mock_producer.cpp]: removed in future pr's

**Review by lukeschmitt-tr — APPROVED** [review]
